version: "3.8"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blobstorage
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/workspace
    command:
      [
        "azurite-blob",
        "--blobHost",
        "0.0.0.0",
        "--blobPort",
        "10000",
        "--location",
        "/workspace",
        "--loose",
      ]

volumes:
  azurite_data:
