#!/bin/sh
# place this script in .git/hooks to enable it, make sure pre-commit it setup.
echo "==============================*Post-commit*=============================="
#echo "=======mypy eval...======="
#mypy .
echo "=======running pytests with coverage...======="
pytest
echo "=======Generate documentation...======"
pdoc -d google src/templator --output-directory ./docs
# echo "=======Updating dependencies...======"
# uv export -o env/requirements.txt
# uv export -o env/requirements-dev.txt --all-extras
exit 0
